Renames to prql-exec

diff --git a/prql-exec b/prql-exec
--- a/prql-exec
+++ b/prql-exec
@@ -1,3 +1,34 @@
+#!/bin/bash
+
+prql-exec "$@"
+
+prql-exec() {
+  # Looks for PRQL_EXEC_COMMAND and passes output to that if present
+  prql-init
+  input=$( ([[ -z "$1" ]] || [[ "$1" == "-" ]] || [[ -f "$1" ]]) && cat "${1:--}" || echo -e "$1" )
+  destinaton="${2:--}"
+  options="${@:3}"
+  prql-lib "$@" 	# TODO: should this use just $input?
+  query="$PRQL_LIB_OUTPUT"
+  prql-compile "$query" "$destination" "$options"
+  if [[ $? -ne 0 ]]; then
+    prql-cleanup
+    return $?
+  fi
+  sql="$PRQL_COMPILE_OUTPUT"
+  echo "$( env | grep PRQL_ )" >&2
+  if [ -n "$PRQL_EXEC_COMMAND" ]; then
+    echo "Using PRQL_EXEC_COMMAND=$PRQL_EXEC_COMMAND" >&2
+    $PRQL_EXEC_COMMAND "$sql"
+  else
+    echo "ERROR: No PRQL_EXEC_COMMAND found!"
+    echo -e "# SQL\n\n$sql"
+    prql-cleanup
+    return 1
+  fi
+  prql-cleanup
+}
+
 prql() { 
   prql-init
   input=$( ([[ -z "$1" ]] || [[ "$1" == "-" ]] || [[ -f "$1" ]]) && cat "${1:--}" || echo -e "$1" )
@@ -40,39 +71,6 @@ prql-compile() {
     echo -e "\n# QUERY\n\n$query\n\n"
     return 1
   fi
-}
-
-prql-git() {
-  # Requires mergestat
-  sql=$(prql-lib "$1" | prqlc compile --target=sql.sqlite --hide-signature-comment)
-  (exit $?) && mergestat "${sql}" ${@:2}
-}
-
-prql-exec() {
-  # Looks for PRQL_EXEC_COMMAND and passes output to that if present
-  prql-init
-  input=$( ([[ -z "$1" ]] || [[ "$1" == "-" ]] || [[ -f "$1" ]]) && cat "${1:--}" || echo -e "$1" )
-  destinaton="${2:--}"
-  options="${@:3}"
-  prql-lib "$@" 	# TODO: should this use just $input?
-  query="$PRQL_LIB_OUTPUT"
-  prql-compile "$query" "$destination" "$options"
-  if [[ $? -ne 0 ]]; then
-    prql-cleanup
-    return $?
-  fi
-  sql="$PRQL_COMPILE_OUTPUT"
-  echo "$( env | grep PRQL_ )" >&2
-  if [ -n "$PRQL_EXEC_COMMAND" ]; then
-    echo "Using PRQL_EXEC_COMMAND=$PRQL_EXEC_COMMAND" >&2
-    $PRQL_EXEC_COMMAND "$sql"
-  else
-    echo "ERROR: No PRQL_EXEC_COMMAND found!"
-    echo -e "# SQL\n\n$sql"
-    prql-cleanup
-    return 1
-  fi
-  prql-cleanup
 }
 
 capitalize() {
