WIP: Fixing nested imports

diff --git a/prql-exec b/prql-exec
--- a/prql-exec
+++ b/prql-exec
@@ -31,70 +31,75 @@ capitalize() {
 }
 
 prql-import() { 
-  # FIXME: Add support for aliases
+  # looks for $name on the $prql_lib_path
+  local import_name="$1"
   local output=""
-  local separator="${2:-__}"
-  local prefix="${3:-$1}"
-  local prql_lib_path="${PRQL_LIB_PATH:-.}"
+  local prql_lib_path="${2:-$PRQL_LIB_PATH}"
+  local separator="${3:-__}"
   local found=false
   PRQL_LIB_PATH=""
   #echo "Using PRQL_LIB_PATH=$prql_lib_path" >&2
   IFS=":"
   for lib_dir in $prql_lib_path; do
-    if ([[ -d "$lib_dir/$1" ]] && [[ -f "$lib_dir/$1/$(capitalize $1).prql" ]]); then
+    if ([[ -d "$lib_dir/$import_name" ]] && [[ -f "$lib_dir/$import_name/$(capitalize $import_name).prql" ]]); then
       # found a library
-      pushd "$lib_dir/$1" > /dev/null
-      prql-lib "$(capitalize $1).prql" "$separator" "$prefix"
+      pushd "$lib_dir/$import_name" > /dev/null
+      prql-lib "$(cat "$(capitalize $import_name).prql")" "." "$separator"
       popd > /dev/null
       output="$PRQL_LIB_OUTPUT"
-      #echo "Imported $lib_dir/$1/$(capitalize $1).prql" >&2
+      #echo "Imported $lib_dir/$import_name/$(capitalize $import_name).prql" >&2
       # Also source .env file if present for prql-exec
-      if [ -f "$lib_dir/$1/.env" ]; then
-        #cat "$lib_dir/$1/.env" >&2
+      if [ -f "$lib_dir/$import_name/.env" ]; then
+        #cat "$lib_dir/$import_name/.env" >&2
 	set -a
-        source "$lib_dir/$1/.env"
+        source "$lib_dir/$import_name/.env"
 	set +a
       fi
       found=true
       break
-    elif [[ -f "$lib_dir/$1.prql" ]]; then
+    elif [[ -f "$lib_dir/$import_name.prql" ]]; then
       # found a module
-      output=$(cat "$lib_dir/$1.prql")
-      #echo "Imported $lib_dir/$1.prql" >&2
+      output=$(cat "$lib_dir/$import_name.prql")
+      #echo "Imported $lib_dir/$import_name.prql" >&2
       found=true
       break
     fi
   done
   if [ "$found" = false ]; then
-    echo "ERROR: Could not import $1."
+    echo "ERROR: Could not import $import_name."
     return 1
   fi
   # apply the prefix to all let statements
-  output=$(echo "$output" | sed -r "s/^let[ ]+/let $prefix$separator/")
+  output=$(echo "$output" | sed -r "s/^[[:space:]]*let[[:space:]]+/let $import_name$separator/")
   PRQL_IMPORT_OUTPUT="$output"
 }
 
 prql-lib() { 
-  local input=$( ([[ -z "$1" ]] || [[ "$1" == "-" ]] || [[ -f "$1" ]]) && cat "${1:--}" || echo -e "$1" )
+  # Looks for import statements in the current input and then calls prql-import for those.
+  local input="$1"
   local output="$input"
-  local separator="${2:-__}"
+  local prql_lib_path="${2:-$PRQL_LIB_PATH}"
+  local separator="${3:-__}"
   # Define the pattern to match lines
   local import_pattern="^import[[:space:]]\{1,\}[[:alnum:]_-]\{1,\}[[:space:]]\{0,\}\(as[[:space:]]\{1,\}[[:alnum:]_-]\{1,\}\)\{0,1\}$"
   # Use sed to extract lines matching the pattern and capture the two words following "import"
   local import_matches=$(echo "$output" | sed -n "/$import_pattern/p")
   # Iterate over the matches using a for loop
   IFS=$'\n'  # Set the Internal Field Separator to newline to iterate over lines
+  local line
   for line in $import_matches; do
     if [[ "$line" =~ ^import[[:space:]]+([[:alnum:]_-]+)[[:space:]]*(as)?[[:space:]]*([[:alnum:]_-]+)?[[:space:]]*$ ]]; then
-      local library_name="${BASH_REMATCH[1]}"
-      local library_alias="${BASH_REMATCH[3]}"
-      local prefix="${3:-$library_name}"
-      prql-import "$library_name" "$separator" "$prefix"
+      local import_name="${BASH_REMATCH[1]}"
+      local import_alias="${BASH_REMATCH[3]:-$import_name}"
+      prql-import "$import_name" "$prql_lib_path" "$separator"
       local import_replacement="$PRQL_IMPORT_OUTPUT"
       # Replace the import statement with the code from the module/library
       output=$(echo "$output" | awk -v import_replacement="$import_replacement" '{gsub("'"$line"'", import_replacement)}1')
       # Replace references to the module/library
-      output=$(echo "$output" | sed -r "s/\<$library_alias\>\./$prefix$separator/g")
+      # This is pretty hacky and unsafe so users should try to avoid name collisions.
+      # Replace tne references
+      # FIXME: these actually need to be captured and passed down the stack
+      output=$(echo "$output" | sed -r "s/([[:space:].]|\b)$import_alias\./\1$import_name$separator/g")
     fi
   done
   PRQL_LIB_OUTPUT="$output"
@@ -106,8 +111,10 @@ prql-exec-fn() {
   local options="${@:2}"
   prql-lib "$input"
   local query="$PRQL_LIB_OUTPUT"
+  #echo -e "$query"
   prql-compile "$query"
   if [[ $? -ne 0 ]]; then
+    echo -e "ERROR: Could not compile query:\n$query"
     return $?
   fi
   local sql="$PRQL_COMPILE_OUTPUT"
